### ISSUE TITLE
Add OpenStack as supported cloud account

### ISSUE THREAD

**Issue by vesper1978** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#138]
Would it be possible to add OpenStack as a supported cloud account? I can see it being something good to have as more and more smaller cloud providers are using OpenStack. 

I'd also recommend being able to add more than 1, as sometimes we need to deploy to multiple OpenStack cloud providers.

**Comment by D10S0VSkY-OSS** [comment]
Ho @vesper1978 ,
You should be able to use it as a custom provider, have you tried this way?
Regards
