### ISSUE TITLE
How to custom terraform command ?

### ISSUE THREAD

**Issue by dehengxu** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#180]
as title mentioned

**Comment by D10S0VSkY-OSS** [comment]
Right now there is no possibility to customize Terraform commands, but I have it on the roadmap

**Comment by dehengxu** [comment]
> Right now there is no possibility to customize Terraform commands, but I have it on the roadmap

SLD features is good now, there is no need to custom terraform commnand
