### ISSUE TITLE
Please wait for API deploy

### ISSUE THREAD

**Issue by Recovzz** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#51]
Hello i have an issue when i download SLD : 

![image](https://user-images.githubusercontent.com/93311330/156740699-e39fa579-4807-4a47-86cf-8e5cf4fb79fc.png)

MY PODS are in PENDING : 

![image](https://user-images.githubusercontent.com/93311330/156740813-75b0a136-2e32-4eff-a31d-8061243d40f0.png)

MY NODES ARE IN NOT READY : 

![image](https://user-images.githubusercontent.com/93311330/156740894-21517fb3-3342-4d41-b285-eb72ed993130.png)

**Comment by D10S0VSkY-OSS** [comment]
@Recovzz 
I can't reproduce the problem

`kind version: kind v0.10.0 go1.15.7 linux/amd64`
![image](https://user-images.githubusercontent.com/79284025/156811931-85cc757b-8578-4b18-ac42-5d2b1b93b974.png)

`SLD latest version`
![image](https://user-images.githubusercontent.com/79284025/156812095-8a938400-7355-4ae5-92e0-6db24bc2d68e.png)
`./kplay.sh init`
![image](https://user-images.githubusercontent.com/79284025/156812222-24cfca57-f2d9-4f36-b4c2-bc4e08b0a944.png)

![image](https://user-images.githubusercontent.com/79284025/156812439-0e1105a0-3110-43ac-aec1-23787e299b84.png)

**Comment by D10S0VSkY-OSS** [comment]
Please could you check your connectivity between kubernetes and dockerhub, a simple test can be by deploying a simple pod
#### Start a single instance of nginx.
`kubectl run nginx --image=nginx`
#### Check that your pod is running
![image](https://user-images.githubusercontent.com/79284025/156813318-7b86ba00-e9f1-4379-8643-9d8bde9fc47b.png)

**Comment by D10S0VSkY-OSS** [comment]
The issue is closed after more than 30 days without updates
