### ISSUE TITLE
Plan stuck in Pending state

### ISSUE THREAD

**Issue by omnikarthik** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#66]
Hi Team, need some help to move further. I added a stack and kicked of a plan and it is stuck in pending state forever.

**Comment by D10S0VSkY-OSS** [comment]
Hi @omnikarthik 
please check that there is a worker listening on the account you have deployed.
in the example in SLD squad1 is used, if you have created an account with another name you have to create a worker capable of managing that account

[Read Usage Readme](https://github.com/D10S0VSkY-OSS/Stack-Lifecycle-Deployment#usage)
