### ISSUE TITLE
Update "Stack" failed

### ISSUE THREAD

**Issue by ramazulay** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#75]
Hi @D10S0VSkY-OSS ,
When I tried to update a "Stack", edit -> "Update" OR click on "sync" the repo I got the error below:
![image](https://user-images.githubusercontent.com/41533452/177286252-c4182e78-6bab-4423-b05f-422cde037262.png)

Logs from sld-dashboard:
- - [05/Jul/2022:10:22:32 +0200] "GET /static/assets/vendor/simplebar/dist/simplebar.min.js HTTP/1.1" 304 0 "http://ac-sld:5000/edit-stack/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
- - - [05/Jul/2022:10:22:32 +0200] "GET /static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js HTTP/1.1" 304 0 "http://ac-sld:5000/edit-stack/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
[2022-07-05 10:23:07 +0200] [1] [CRITICAL] WORKER TIMEOUT (pid:22)
[2022-07-05 10:23:07 +0200] [1] [CRITICAL] WORKER TIMEOUT (pid:24)
[2022-07-05 10:23:07 +0200] [22] [INFO] Worker exiting (pid: 22)
[2022-07-05 10:23:07 +0200] [24] [INFO] Worker exiting (pid: 24)
[2022-07-05 10:23:07 +0200] [25] [INFO] Booting worker with pid: 25
[2022-07-05 10:23:07 +0200] [1] [WARNING] Worker with pid 24 was terminated due to signal 9
[2022-07-05 10:23:07 +0200] [26] [INFO] Booting worker with pid: 26

Thanks for your help.

**Comment by D10S0VSkY-OSS** [comment]
Hi @ramazulay ,
Please, could you tell me what version of SLD are you using?
Regards,

**Comment by ramazulay** [comment]
Hi @D10S0VSkY-OSS,
The version is d10s0vsky/sld-dashboard:2.3.0 and d10s0vsky/sld-api:2.3.0.
After your updated the tfvar_file here.[https://github.com/D10S0VSkY-OSS/Stack-Lifecycle-Deployment/discussions/62](url)

**Comment by D10S0VSkY-OSS** [comment]
Hi @ramazulay 
please try to **update** to version **d10s0vsky/sld-api:2.5.0** and  **d10s0vsky/sld-dashboard:2.4.0**.
Just note that there is a **bracking change** that adds another field to the "stack_branch" database that allows you to specify an individual branch for each deploy.
Try add the field
```
ALTER TABLE deploy ADD stack_branch varchar(100) NULL AFTER stack_name;
```

**Comment by ramazulay** [comment]
Hi @D10S0VSkY-OSS,
I have updated as you requested.(of course i did rollout restart)
I run the ALTER command also.(of course i did rollout restart)
The Sync still failed.

Log from sld-dashboard:
[2022-07-11 10:23:31 +0200] [1] [CRITICAL] WORKER TIMEOUT (pid:11)
[2022-07-11 10:23:31 +0200] [11] [INFO] Worker exiting (pid: 11)
[2022-07-11 10:23:31 +0200] [1] [CRITICAL] WORKER TIMEOUT (pid:13)
[2022-07-11 10:23:31 +0200] [13] [INFO] Worker exiting (pid: 13)
[2022-07-11 10:23:31 +0200] [14] [INFO] Booting worker with pid: 14
[2022-07-11 10:23:31 +0200] [1] [WARNING] Worker with pid 13 was terminated due to signal 9
[2022-07-11 10:23:31 +0200] [15] [INFO] Booting worker with pid: 15
[2022-07-11 10:24:02 +0200] [1] [CRITICAL] WORKER TIMEOUT (pid:12)

**Comment by D10S0VSkY-OSS** [comment]
Hi @ramazulay 
please, check that the workers use the docker image d10s0vsky/sld-api:2.5.0 too.
Regards

**Comment by ramazulay** [comment]
When I edit the deploy I got:
![image](https://user-images.githubusercontent.com/41533452/178444696-df572520-97ff-4b0a-b44a-594a8a2c87b6.png)
Very strange.

**Comment by D10S0VSkY-OSS** [comment]
@ramazulay 
I have released a fix, please update to **d10s0vsky/sld-dashboard:tagname:2.4.1**
regards

**Comment by ramazulay** [comment]
Hi @D10S0VSkY-OSS,
I reinstalled the sld on another ns and I have seeing the same issue(Update/create/sync stuck "Stack")
Thanks.

**Comment by D10S0VSkY-OSS** [comment]
Hi @ramazulay ,
please, Coud you send me the output next command:
```
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c|grep d10s

**Comment by D10S0VSkY-OSS** [comment]
file:///home/d10s/Downloads/Screencast%20from%2014-07-22%2015_06_22.gif

**Comment by D10S0VSkY-OSS** [comment]
[Screencast from 14-07-22 15:06:22.webm](https://user-images.githubusercontent.com/79284025/178990672-bd050e48-cf4f-4014-aa01-3dfc1469c529.webm)

**Comment by ramazulay** [comment]
Hi @D10S0VSkY-OSS,
Thanks for your replay.
The output command:
> tr -s '[[:space:]]' '\n' |\
> sort |\
> uniq -c|grep d10s
      2 d10s0vsky/sld-api:2.5.0
      1 d10s0vsky/sld-dashboard:2.4.1
      1 d10s0vsky/sld-remote-state:1.0.2
      1 d10s0vsky/sld-schedule:latest

Thanks.

**Comment by D10S0VSkY-OSS** [comment]
@ramazulay 
apparently you have everything correct, unfortunately I am not able to reproduce your problem.
Have you tried with a completely new database?
Regards,

**Comment by ramazulay** [comment]
Hi @D10S0VSkY-OSS,
Yes, I`ve deleted the PVC and redeployed the DB.
I also reverted to the latest version, but without success.

What do you recommend to do?

**Comment by D10S0VSkY-OSS** [comment]
@ramazulay,
If you can, send me a schedule meet to my email and we try to solve it in a meet.
please, remember that I live in Spain Central European Time (CET), UTC +1
Regars

**Comment by D10S0VSkY-OSS** [comment]
After having a meet with @ramazulay  we have been able to see that the worker default was missing, in charge of generating the stack
